version: "3"
services:
  client:
    build:
      context: ../client/my-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    build:
      context: ../data
      dockerfile: Dockerfile
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
volumes:
  data:
